{{- if and (not .Values.ssh_key)  (and (not .Values.username) (not .Values.password) )}}
  {{required "Either the ssh_key or username/password values are required" .Values.ssh_key}}
{{- end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranvier
  labels:
    app: ranvier
spec:
  replicas: 1
  template:
    metadata:
      name: ranvier
      labels:
        app: ranvier
    spec:
      containers:
        - name: ranvier
          image: {{.Values.container.image.name}}:{{.Values.container.image.tag}}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.memory}}
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
          ports:
            - containerPort: {{.Values.container.port}}
          env:
            - name: RANVIER_GIT_USERNAME
              value: {{.Values.username}}
            {{- if .Values.ssh_key}}
            - name: RANVIER_GIT_SSHKEY
              value: /.ssh/id_rsa
            {{else}}
            - name: RANVIER_GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{.Values.secret.git_access.name}}
            {{end}}
          {{- if .Values.ssh_key}}
          volumeMounts:
            - mountPath: /
              name: ssh_key
          {{end}}
      {{- if .Values.ssh_key}}
      volumes:
        - name: ssh_key
          secret:
            secretName: {{.Values.secret.git_access.name}}
            items:
              - key: ssh_key
                path: .ssh
                mode: 600
      {{end}}
      restartPolicy: Always
  selector:
    matchLabels:
      app: ranvier