apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranvier
  labels:
    app: ranvier
spec:
  replicas: 1
  template:
    metadata:
      name: ranvier
      labels:
        app: ranvier
    spec:
      containers:
        - name: ranvier
          image: {{.Values.container.image.name}}:{{.Values.container.image.tag}}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.memory}}
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
          ports:
            - containerPort: {{.Values.container.port}}
          env:
                  {{- if or .Values.ssh_key  (and (eq .Values.username "") (eq .Values.password "") )}}
                  {{required "Either the ssh_key or username/password values are required" .Values.ssh_key}}
                  {{- else}}
                  {{- if .Values.ssh_key}}
            - name: RANVIER_GIT_SSH_KEY
              value: {{.Values.ssh_key}}
                  {{- else}}
            - name: RANVIER_GIT_USERNAME
              value: {{.Values.username}}
            - name: RANVIER_GIT_PASSWORD
              value: {{.Values.password}}
                  {{- end}}
            {{- end}}

      restartPolicy: Always
  selector:
    matchLabels:
      app: ranvier