apiVersion: v1
kind: Service
metadata:
  name: ranvier
spec:
  selector:
    app: ranvier
  ports:
    - name: http
      port: 80
      targetPort: {{.Values.container.port}}
    - name: https
      port: 443
      targetPort: {{.Values.container.port}}
  type: {{.Values.svc.type}}