apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranvier
  labels:
    app: ranvier
spec:
  replicas: 1
  template:
    metadata:
      name: ranvier
      labels:
        app: ranvier
    spec:
      containers:
        - name: ranvier
          image: edwardrowens/ranvier-server:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
          ports:
            - containerPort: 8080
          env:
            - name: RANVIER_GIT_USERNAME
              value: <git username>
            - name: RANVIER_GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: <key here>
                  name: <secret name here>
      restartPolicy: Always
  selector:
    matchLabels:
      app: ranvier